# Generated by Django 6.0 on 2026-07-24
# Phase 2, Stage 3, step 9 — branch identity & enrolment (see PHASE2_DESIGN §2.3).

import apps.sync.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_branch_cloud_id_branch_is_active_branch_is_hq_and_more'),
        ('sync', '0002_outboxentry_schema_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=apps.sync.models.generate_enrolment_code, max_length=16, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.sync.models.default_enrolment_expiry)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_codes', to='auth_users.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
