# Generated by Django 6.0 on 2026-07-24
# Phase 2, Stage 3, step 10 — cloud push idempotency ledger (PHASE2_DESIGN §2.4).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_enrolmentcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(db_index=True, max_length=64)),
                ('outbox_id', models.UUIDField(db_index=True)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('operation', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('branch_id', 'outbox_id'), name='uniq_applied_entry_per_branch_outbox')],
            },
        ),
    ]
