# Generated by Django 6.0 on 2026-07-24
# Phase 2, Stage 3, step 11 — outbox push loop state (PHASE2_DESIGN §2.7).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_appliedentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_server_time', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='outboxentry',
            name='rejected_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
