# Generated by Django 6.0 on 2026-07-24
# Phase 2, Stage 3, step 9 — branch identity & enrolment (see PHASE2_DESIGN §2.3).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cloud_id',
            field=models.CharField(blank=True, db_index=True, help_text='Canonical branch_id issued by the cloud at enrolment.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='sync_token',
            field=models.CharField(blank=True, help_text='Device sync token (write-only).', max_length=64, null=True, unique=True),
        ),
    ]
